### ISSUE TITLE
hello ，why ？ donot start up？

### ISSUE THREAD

**Issue by nysyxxg** [alchemystar/Rider#3]
D:\MyNosql\Rider\target\rider\conf
19:14:03.575 [Thread-0] INFO  a.engine.server.RiderServer - Start The Rider
19:14:03.582 [Thread-0] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
19:14:03.583 [Thread-0] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
19:14:03.600 [Thread-0] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
19:14:03.600 [Thread-0] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
Load config errororg.dom4j.DocumentException: null Nested exception: null
请按任意键继续. . .

**Comment by nysyxxg** [comment]
我知道了

**Comment by alchemystar** [comment]
okay
